"""Add type field to Car model

Revision ID: 2381705d512a
Revises: 54335f819e8d
Create Date: 2025-10-28 14:31:21.230557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2381705d512a'
down_revision = '54335f819e8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testimonial')
    op.drop_table('messages')
    op.drop_table('sell_requests')
    op.drop_table('cars')
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_column('type')

    op.create_table('cars',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('brand', sa.TEXT(), nullable=True),
    sa.Column('year', sa.INTEGER(), nullable=True),
    sa.Column('price', sa.REAL(), nullable=True),
    sa.Column('fuel_type', sa.TEXT(), nullable=True),
    sa.Column('transmission', sa.TEXT(), nullable=True),
    sa.Column('mileage', sa.TEXT(), nullable=True),
    sa.Column('location', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('image1', sa.TEXT(), nullable=True),
    sa.Column('image2', sa.TEXT(), nullable=True),
    sa.Column('image3', sa.TEXT(), nullable=True),
    sa.Column('image4', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sell_requests',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('user_name', sa.TEXT(), nullable=False),
    sa.Column('contact_number', sa.TEXT(), nullable=True),
    sa.Column('email', sa.TEXT(), nullable=True),
    sa.Column('car_brand', sa.TEXT(), nullable=True),
    sa.Column('car_model', sa.TEXT(), nullable=True),
    sa.Column('year', sa.INTEGER(), nullable=True),
    sa.Column('price', sa.REAL(), nullable=True),
    sa.Column('mileage', sa.TEXT(), nullable=True),
    sa.Column('fuel_type', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('image', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('username', sa.TEXT(), nullable=False),
    sa.Column('email', sa.TEXT(), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('testimonial',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('customer_name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('visible', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
